import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

export function registerPrompts(mcp: McpServer): void {
  // ── 1. smoke-test ───────────────────────────────────────────────────────────

  mcp.registerPrompt(
    'smoke-test',
    {
      title: 'Smoke Test',
      description:
        'Quick smoke test of a URL: navigate, screenshot, check console errors, check network for 4xx/5xx, visit key linked pages, and report issues.',
      argsSchema: {
        url: z.string().describe('The URL to smoke-test'),
      },
    },
    ({ url }) => ({
      messages: [
        {
          role: 'user' as const,
          content: {
            type: 'text' as const,
            text: [
              `Perform a smoke test on: ${url}`,
              '',
              'Follow these steps:',
              '',
              `1. Use browser_navigate to go to ${url}. Take a browser_screenshot of the landing page.`,
              '',
              '2. Check the browser console for errors by calling browser_evaluate with the expression:',
              '   `(function(){ var errors = []; var origError = console.error; console.error = function(){ errors.push(Array.from(arguments).join(" ")); origError.apply(console, arguments); }; return JSON.stringify(errors); })()`',
              '   Also review any console_errors returned in the navigate response.',
              '',
              '3. Use network_get_requests to retrieve all captured HTTP requests. Filter for any responses with status codes in the 4xx or 5xx range (use statusMin: 400). Report each failed request.',
              '',
              '4. Identify key internal links on the page using browser_accessibility_tree or browser_evaluate to extract anchor hrefs. Navigate to 3-5 of the most important linked pages (e.g. main navigation items). On each page:',
              '   - Take a browser_screenshot',
              '   - Check network_get_requests for 4xx/5xx errors',
              '   - Check for console errors via browser_evaluate',
              '',
              '5. For every issue found (console errors, network failures, broken pages, visual anomalies), use report_create_bug to file a bug with:',
              '   - A descriptive title',
              '   - severity: "major" for 5xx errors or page crashes, "minor" for 4xx or console warnings',
              '   - stepsToReproduce: the navigation steps to reach the issue',
              '   - expected: what should happen',
              '   - actual: what actually happened',
              '   - url: the page URL where the issue occurred',
              '',
              '6. At the end, call report_get_session_summary to generate a summary of everything found.',
            ].join('\n'),
          },
        },
      ],
    }),
  );

  // ── 2. full-qa ──────────────────────────────────────────────────────────────

  mcp.registerPrompt(
    'full-qa',
    {
      title: 'Full QA',
      description:
        'Comprehensive QA pass: explore all pages, test forms, check accessibility, test responsive behavior, verify links, and generate an HTML report.',
      argsSchema: {
        url: z.string().describe('The starting URL to test'),
        scope: z
          .string()
          .optional()
          .describe(
            'Optional focus area or scope description (e.g. "checkout flow", "admin dashboard")',
          ),
      },
    },
    ({ url, scope }) => ({
      messages: [
        {
          role: 'user' as const,
          content: {
            type: 'text' as const,
            text: [
              `Perform a comprehensive QA pass on: ${url}`,
              scope ? `Focus area: ${scope}` : '',
              '',
              'Follow these steps systematically:',
              '',
              '## Page Exploration',
              `1. Use browser_navigate to go to ${url}. Take a browser_screenshot.`,
              '2. Use browser_accessibility_tree to understand the page structure.',
              '3. Extract all internal links using browser_evaluate (document.querySelectorAll("a[href]")). Systematically visit every reachable page from the starting URL. On each page:',
              '   - Take a browser_screenshot',
              '   - Use browser_accessibility_tree to inspect the page',
              '   - Check network_get_requests for failed requests (statusMin: 400)',
              '   - Check console errors via browser_evaluate',
              '',
              '## Form Testing',
              '4. On every page, identify all forms using browser_accessibility_tree or browser_evaluate.',
              '5. For each form found, test with:',
              '   a. Empty submission: click submit without filling any fields. Check for proper validation messages.',
              '   b. Valid data: use browser_fill to enter valid, realistic data in each field. Submit and verify success.',
              '   c. Invalid data: use browser_fill with invalid email formats, negative numbers, etc. Verify proper error handling.',
              '',
              '## Accessibility',
              '6. On every page, call browser_accessibility_tree and check for:',
              '   - Elements missing accessible names or labels',
              '   - Images without alt text (check via browser_evaluate: document.querySelectorAll("img:not([alt])"))',
              '   - Form inputs without associated labels',
              '   Use report_add_finding with category "accessibility" for each issue.',
              '',
              '## Responsive Testing',
              '7. On key pages, test responsive behavior:',
              '   - Use browser_resize with width: 375, height: 667 (mobile). Take a browser_screenshot.',
              '   - Check for horizontal overflow via browser_evaluate: document.documentElement.scrollWidth > document.documentElement.clientWidth',
              '   - Use browser_resize with width: 1280, height: 720 to restore desktop. Take a browser_screenshot.',
              '',
              '## Link Verification',
              '8. Collect all links on each page. Use browser_navigate to visit each one. Check that none return 4xx/5xx via network_get_requests.',
              '',
              '## Console Error Monitoring',
              '9. On every page visited, check for console errors. Aggregate all unique errors.',
              '',
              '## Reporting',
              '10. For every bug found, use report_create_bug with appropriate severity:',
              '    - critical: app crashes, data loss, security issues',
              '    - major: broken functionality, 5xx errors',
              '    - minor: 4xx errors, validation issues, minor UI problems',
              '    - cosmetic: styling inconsistencies, typos',
              '',
              '11. For UX observations and accessibility concerns, use report_add_finding.',
              '',
              '12. At the end, call report_generate with format "html" to produce the final QA report.',
            ].join('\n'),
          },
        },
      ],
    }),
  );

  // ── 3. regression-test ──────────────────────────────────────────────────────

  mcp.registerPrompt(
    'regression-test',
    {
      title: 'Regression Test',
      description:
        'Regression test: perform common user flows, verify expected behavior, compare against a baseline session, and flag deviations.',
      argsSchema: {
        url: z.string().describe('The URL to test'),
        baseline_session_id: z
          .string()
          .optional()
          .describe('Optional session ID of a previous baseline run to compare against'),
      },
    },
    ({ url, baseline_session_id }) => ({
      messages: [
        {
          role: 'user' as const,
          content: {
            type: 'text' as const,
            text: [
              `Perform a regression test on: ${url}`,
              baseline_session_id ? `Baseline session for comparison: ${baseline_session_id}` : '',
              '',
              'Follow these steps:',
              '',
              '## Navigation and Page Verification',
              `1. Use browser_navigate to go to ${url}. Take a browser_screenshot.`,
              '2. Verify the page loads successfully (no 5xx errors in network_get_requests, no critical console errors).',
              '3. Use browser_accessibility_tree to catalog the page structure.',
              '',
              '## Common User Flows',
              '4. Identify the main navigation items and visit each top-level page:',
              '   - Use browser_click on navigation links',
              '   - Take a browser_screenshot on each page',
              '   - Verify the page title and URL are correct via browser_evaluate',
              '',
              '5. Locate and test key forms on the site:',
              '   - Use browser_fill to enter valid data',
              '   - Submit forms and verify success responses',
              '   - Check network_get_requests for the form submission API calls and verify they return 2xx status codes',
              '',
              '6. Verify critical API responses:',
              '   - Use network_get_requests with resourceType "xhr" or "fetch" to inspect API calls',
              '   - Confirm response statuses are as expected',
              '   - Check response payloads via browser_evaluate if needed',
              '',
              '## Baseline Comparison',
              baseline_session_id
                ? [
                    `7. Compare current behavior against baseline session ${baseline_session_id}:`,
                    '   - Check that the same pages are reachable',
                    '   - Verify that forms still work as in the baseline',
                    '   - Compare page structures using browser_accessibility_tree',
                    '   - Flag any pages that previously loaded but now fail',
                    '   - Flag any new console errors not present in the baseline',
                  ].join('\n')
                : '7. Since no baseline session was provided, document the current behavior as the baseline for future runs.',
              '',
              '## Deviation Reporting',
              '8. For any deviation from expected behavior or from the baseline, use report_create_bug:',
              '   - severity: "critical" if core functionality is broken',
              '   - severity: "major" if secondary functionality regressed',
              '   - severity: "minor" for cosmetic or non-blocking regressions',
              '   - Include stepsToReproduce detailing the exact flow',
              '   - Include expected (baseline behavior) vs actual (current behavior)',
              '',
              '9. Use report_add_finding for non-bug observations (e.g. performance changes, UX differences).',
              '',
              '10. Call report_get_session_summary at the end to produce a regression summary.',
            ].join('\n'),
          },
        },
      ],
    }),
  );

  // ── 4. accessibility-audit ──────────────────────────────────────────────────

  mcp.registerPrompt(
    'accessibility-audit',
    {
      title: 'Accessibility Audit',
      description:
        'Audit a page for accessibility: check ARIA labels, alt text, contrast, keyboard navigation, and record violations.',
      argsSchema: {
        url: z.string().describe('The URL to audit for accessibility'),
      },
    },
    ({ url }) => ({
      messages: [
        {
          role: 'user' as const,
          content: {
            type: 'text' as const,
            text: [
              `Perform an accessibility audit on: ${url}`,
              '',
              'Follow these steps:',
              '',
              '## Page Setup',
              `1. Use browser_navigate to go to ${url}. Take a browser_screenshot.`,
              '',
              '## Accessibility Tree Analysis',
              '2. Call browser_accessibility_tree to get the full accessibility tree.',
              '3. Analyze the tree for:',
              '   - Interactive elements (buttons, links, inputs) missing accessible names',
              '   - Elements with generic or non-descriptive roles',
              '   - Missing or incorrect ARIA attributes',
              '   Record each violation using report_add_finding with category "accessibility".',
              '',
              '## Alt Text Check',
              '4. Use browser_evaluate to find images missing alt text:',
              '   `document.querySelectorAll("img:not([alt]), img[alt=\\"\\"]").length`',
              '   For each image without alt text, record a report_add_finding with category "accessibility" including the image src.',
              '',
              '## Contrast Check',
              '5. Use browser_evaluate to check text contrast ratios. Run a script that:',
              '   - Selects all text elements',
              '   - Computes foreground and background colors using getComputedStyle',
              '   - Calculates the contrast ratio',
              '   - Flags elements with contrast ratio below 4.5:1 (WCAG AA for normal text) or 3:1 (for large text)',
              '   Record each low-contrast element as a report_add_finding with category "accessibility".',
              '',
              '## Keyboard Navigation',
              '6. Test keyboard navigation by:',
              '   - Use browser_press with key "Tab" repeatedly to cycle through focusable elements',
              '   - After each Tab press, use browser_evaluate to check document.activeElement and verify:',
              '     a. A visible focus indicator exists (outline, border, etc.)',
              '     b. The tab order is logical (follows visual layout)',
              '     c. No keyboard traps (can always Tab away from an element)',
              '   - Use browser_press with key "Enter" on interactive elements to verify they activate',
              '   - Take browser_screenshot at key points to document focus states',
              '   Record keyboard navigation issues as report_add_finding with category "accessibility".',
              '',
              '## Form Label Association',
              '7. Use browser_evaluate to check that every form input has an associated label:',
              '   `document.querySelectorAll("input:not([type=hidden]), select, textarea").forEach(el => { ... })`',
              '   Check for: matching <label for="...">, aria-label, aria-labelledby, or wrapping <label>.',
              '   Record missing label associations as report_add_finding with category "accessibility".',
              '',
              '## Heading Structure',
              '8. Use browser_evaluate to verify heading hierarchy:',
              '   - Check that there is exactly one h1',
              '   - Check that heading levels do not skip (e.g. h1 -> h3 without h2)',
              '   Record heading structure issues as report_add_finding with category "accessibility".',
              '',
              '## Summary',
              '9. Call report_get_session_summary to produce the audit results.',
            ].join('\n'),
          },
        },
      ],
    }),
  );

  // ── 5. form-test ────────────────────────────────────────────────────────────

  mcp.registerPrompt(
    'form-test',
    {
      title: 'Form Test',
      description:
        'Test forms with empty, valid, invalid, XSS, and boundary-value inputs. File bugs for validation failures.',
      argsSchema: {
        url: z.string().describe('The URL containing forms to test'),
        form_selector: z
          .string()
          .optional()
          .describe(
            'Optional CSS selector to target a specific form (defaults to testing all forms on the page)',
          ),
      },
    },
    ({ url, form_selector }) => ({
      messages: [
        {
          role: 'user' as const,
          content: {
            type: 'text' as const,
            text: [
              `Perform form testing on: ${url}`,
              form_selector ? `Target form: ${form_selector}` : 'Test all forms found on the page.',
              '',
              'Follow these steps:',
              '',
              '## Form Discovery',
              `1. Use browser_navigate to go to ${url}. Take a browser_screenshot.`,
              '2. Use browser_accessibility_tree to identify all forms on the page.',
              form_selector
                ? `3. Focus on the form matching selector: ${form_selector}`
                : '3. For each form found, run the following test scenarios:',
              '',
              '## Test Scenario 1: Empty Submission',
              '4. Without filling any fields, locate the submit button and use browser_click to submit the form.',
              '5. Take a browser_screenshot to capture validation messages.',
              '6. Use browser_evaluate to check for HTML5 validation (element.validity) and custom error messages.',
              '7. Verify that required fields show appropriate error messages. If the form submits without validation, use report_create_bug with severity "major".',
              '',
              '## Test Scenario 2: Valid Data',
              '8. Use browser_fill to populate each field with valid, realistic data:',
              '   - Text fields: realistic names, addresses',
              '   - Email fields: valid email format (e.g. test@example.com)',
              '   - Phone fields: valid phone format',
              '   - Number fields: values within expected range',
              '   - Select fields: use browser_select to choose a valid option',
              '9. Take a browser_screenshot of the filled form.',
              '10. Submit the form with browser_click. Verify success via:',
              '    - Check network_get_requests for the form POST/submission and confirm a 2xx response',
              '    - Check for a success message on the page via browser_evaluate',
              '    - Take a browser_screenshot of the result',
              '',
              '## Test Scenario 3: Invalid Data',
              '11. Re-navigate to the form if needed (browser_navigate or browser_back).',
              '12. Use browser_fill to enter invalid data:',
              '    - Email fields: "not-an-email", "@missing-local", "no-at-sign.com"',
              '    - Number fields: negative numbers, letters, extremely large numbers',
              '    - Date fields: invalid dates (e.g. "2024-13-45")',
              '    - Required fields: leave some empty while filling others',
              '13. Submit and verify that the form rejects invalid input with appropriate messages.',
              '14. If invalid data is accepted, use report_create_bug with severity "major".',
              '',
              '## Test Scenario 4: XSS Payloads',
              '15. Re-navigate to the form.',
              '16. Use browser_fill to enter XSS test payloads in all text/textarea fields:',
              '    - <script>alert("xss")</script>',
              '    - <img src=x onerror=alert("xss")>',
              '    - javascript:alert("xss")',
              '    - "><svg onload=alert("xss")>',
              '17. Submit the form. After submission:',
              '    - Check the response page via browser_evaluate for any reflected, unescaped HTML',
              '    - Check if any script elements were injected into the DOM',
              '    - If XSS payload is reflected unescaped, use report_create_bug with severity "critical"',
              '',
              '## Test Scenario 5: Boundary Values',
              '18. Re-navigate to the form.',
              '19. Use browser_fill to test boundary conditions:',
              '    - Very long strings (1000+ characters) in text fields',
              '    - Single character inputs',
              '    - Unicode characters and emoji',
              '    - SQL-like strings (e.g. "\' OR 1=1 --")',
              '    - Leading/trailing whitespace',
              '20. Submit and check for proper handling. If the application crashes or returns a 5xx, use report_create_bug with severity "critical".',
              '',
              '## Summary',
              '21. Take a final browser_screenshot.',
              '22. Call report_get_session_summary to review all bugs and findings.',
            ].join('\n'),
          },
        },
      ],
    }),
  );

  // ── 6. performance-check ────────────────────────────────────────────────────

  mcp.registerPrompt(
    'performance-check',
    {
      title: 'Performance Check',
      description:
        'Check page performance: slow network responses, large payloads, page load timing, excessive DOM nodes, and record findings.',
      argsSchema: {
        url: z.string().describe('The URL to check for performance'),
      },
    },
    ({ url }) => ({
      messages: [
        {
          role: 'user' as const,
          content: {
            type: 'text' as const,
            text: [
              `Perform a performance check on: ${url}`,
              '',
              'Follow these steps:',
              '',
              '## Page Load',
              `1. Use browser_navigate to go to ${url} with waitUntil "networkidle". Take a browser_screenshot.`,
              '',
              '## Network Performance',
              '2. Use network_get_requests to get all captured requests.',
              '3. Analyze the results for:',
              '   - Slow responses: any request taking longer than 3 seconds (check duration field)',
              '   - Large payloads: responses larger than 1MB (check response size)',
              '   - Failed requests: any 4xx or 5xx status codes',
              '   - Excessive number of requests (more than 100 total requests)',
              '   For each slow or oversized request, use report_add_finding with category "performance" including the URL, duration, and size.',
              '',
              '## Page Load Timing',
              '4. Use browser_evaluate to get detailed timing metrics:',
              '   ```',
              '   JSON.stringify((() => {',
              '     const t = performance.timing;',
              '     return {',
              '       dns: t.domainLookupEnd - t.domainLookupStart,',
              '       tcp: t.connectEnd - t.connectStart,',
              '       ttfb: t.responseStart - t.requestStart,',
              '       download: t.responseEnd - t.responseStart,',
              '       domInteractive: t.domInteractive - t.navigationStart,',
              '       domComplete: t.domComplete - t.navigationStart,',
              '       fullLoad: t.loadEventEnd - t.navigationStart,',
              '     };',
              '   })())',
              '   ```',
              '   Flag any metric that seems excessive:',
              '   - TTFB > 800ms',
              '   - DOM interactive > 3000ms',
              '   - Full load > 5000ms',
              '   Record as report_add_finding with category "performance".',
              '',
              '## DOM Complexity',
              '5. Use browser_evaluate to check DOM size:',
              '   `document.querySelectorAll("*").length`',
              '   If the DOM has more than 1500 nodes, record a report_add_finding with category "performance" noting the count.',
              '',
              '6. Check for deeply nested DOM trees:',
              '   Use browser_evaluate to find the maximum DOM depth:',
              '   ```',
              '   (function getMaxDepth(el, depth) {',
              '     return el.children.length === 0 ? depth : Math.max(...Array.from(el.children).map(c => getMaxDepth(c, depth + 1)));',
              '   })(document.body, 0)',
              '   ```',
              '   If depth exceeds 32, record as a finding.',
              '',
              '## Resource Analysis',
              '7. Use network_get_requests with resourceType "image" to check for unoptimized images.',
              '8. Use network_get_requests with resourceType "script" to check for large JavaScript bundles.',
              '9. Use network_get_requests with resourceType "stylesheet" to check for large CSS files.',
              '   Record any resource over 500KB as a report_add_finding with category "performance".',
              '',
              '## Memory and Runtime',
              '10. Use browser_evaluate to check for potential memory issues:',
              '    `JSON.stringify({ jsHeapSize: performance.memory?.usedJSHeapSize, totalHeap: performance.memory?.totalJSHeapSize })`',
              '    Record heap usage findings if available.',
              '',
              '## Summary',
              '11. Call report_get_session_summary to produce the performance analysis.',
            ].join('\n'),
          },
        },
      ],
    }),
  );

  // ── 7. visual-inventory ─────────────────────────────────────────────────────

  mcp.registerPrompt(
    'visual-inventory',
    {
      title: 'Visual Inventory',
      description:
        'Build a visual catalog of the site: screenshot every page at desktop, tablet, and mobile breakpoints.',
      argsSchema: {
        url: z.string().describe('The starting URL for the visual inventory'),
      },
    },
    ({ url }) => ({
      messages: [
        {
          role: 'user' as const,
          content: {
            type: 'text' as const,
            text: [
              `Build a visual inventory of the site starting at: ${url}`,
              '',
              'Follow these steps:',
              '',
              '## Setup',
              `1. Use browser_navigate to go to ${url}.`,
              '',
              '## Desktop Viewport (1280x720)',
              '2. Use browser_resize with width: 1280, height: 720.',
              '3. Take a browser_screenshot with fullPage: true to capture the entire page at desktop size.',
              '',
              '## Tablet Viewport (768x1024)',
              '4. Use browser_resize with width: 768, height: 1024.',
              '5. Take a browser_screenshot with fullPage: true to capture the page at tablet size.',
              '',
              '## Mobile Viewport (375x667)',
              '6. Use browser_resize with width: 375, height: 667.',
              '7. Take a browser_screenshot with fullPage: true to capture the page at mobile size.',
              '',
              '## Restore Desktop',
              '8. Use browser_resize with width: 1280, height: 720 to return to desktop.',
              '',
              '## Discover and Catalog All Internal Pages',
              '9. Use browser_evaluate to extract all internal links from the page:',
              '   ```',
              '   JSON.stringify([...new Set(',
              '     Array.from(document.querySelectorAll("a[href]"))',
              '       .map(a => a.href)',
              '       .filter(h => h.startsWith(location.origin))',
              '   )])',
              '   ```',
              '',
              '10. For each internal link discovered:',
              '    a. Use browser_navigate to visit the page.',
              '',
              '    b. Desktop capture:',
              '       - Ensure viewport is at 1280x720 (browser_resize if needed)',
              '       - Take a browser_screenshot with fullPage: true',
              '',
              '    c. Tablet capture:',
              '       - Use browser_resize with width: 768, height: 1024',
              '       - Take a browser_screenshot with fullPage: true',
              '',
              '    d. Mobile capture:',
              '       - Use browser_resize with width: 375, height: 667',
              '       - Take a browser_screenshot with fullPage: true',
              '',
              '    e. Restore to desktop: browser_resize with width: 1280, height: 720',
              '',
              '    f. On each newly discovered page, extract any additional internal links not yet visited. Continue until all reachable pages have been cataloged.',
              '',
              '## Record Observations',
              '11. While capturing, note any visual issues:',
              '    - Layout breakage at certain breakpoints (use report_add_finding with category "usability")',
              '    - Content overflow or horizontal scrolling on mobile',
              '    - Missing responsive behavior (elements not adapting)',
              '    - Broken images or missing assets',
              '',
              '## Summary',
              '12. Call report_get_session_summary to see the total number of pages captured and any findings.',
              '13. Use report_generate with format "html" to produce a visual report with all screenshots embedded.',
            ].join('\n'),
          },
        },
      ],
    }),
  );
}
